
modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory
license="MIT License"

[[mods]] #mandatory

modId="bocchitherock" #mandatory

version="${mod_version}" #mandatory

displayName="Bocchoi The Rock!" #mandatory

authors="${mod_authors}" #optional

description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.2,)"
    ordering="NONE"
    side="BOTH"
